export const COMMON_CONTENT = {
  appName: 'Foodify',
  loading: 'Loading...',
  save: 'Save',
  cancel: 'Cancel',
  create: 'Create',
  update: 'Update',
  delete: 'Delete',
  edit: 'Edit',
  close: 'Close',
  previous: 'Previous',
  next: 'Next',
  goHome: 'Go home',
  refreshPage: 'Refresh page',
}

export const VALIDATION_CONTENT = {
  emailRequired: 'Email is required',
  emailInvalid: 'Enter a valid email address',
  passwordRequired: 'Password is required',
  passwordRules:
    'Password must be at least 8 characters and include an uppercase letter, a number, and a special character',
  confirmPasswordRequired: 'Please confirm your password',
  passwordsMismatch: 'Passwords do not match',
  required: (label) => `${label} is required`,
  phoneInvalid: 'Phone must be in international format (e.g. +14155552671)',
  otpRequired: 'Please enter the complete 6-digit OTP',
  otpInvalid: 'Invalid OTP. Please check and try again.',
}

export const AUTH_CONTENT = {
  loginTitle: 'Welcome back',
  loginDescription: 'Sign in to your restaurant dashboard',
  loginButton: 'Login',
  loginLoading: 'Signing in...',
  rememberMe: 'Remember me',
  forgotPassword: 'Forgot password?',
  noAccount: "Don't have an account?",
  signupLink: 'Sign up',

  signupTitle: 'Create your account',
  signupDescription: 'Register your restaurant on Foodify',
  signupButton: 'Sign Up',
  signupLoading: 'Creating account...',
  hasAccount: 'Already have an account?',
  loginLink: 'Login',
  restaurantName: 'Restaurant Name',
  confirmPassword: 'Confirm Password',

  otpTitle: 'Verify your email',
  otpDescription: 'Enter the 6-digit code sent to',
  otpLabel: 'Verification code',
  verifyButton: 'Verify OTP',
  verifyLoading: 'Verifying...',
  backToSignup: 'Back to sign up',
  otpExpiresIn: 'Code expires in',
  otpExpired: 'Your verification code has expired.',
  otpExpiredAction: 'Request a new code to continue.',
  resendOtp: 'Resend OTP',
  resendOtpLoading: 'Sending...',
  resendOtpSuccess: 'A new OTP has been sent to your email.',
  resendOtpCooldown: 'Resend available in',
  resendOtpDisabled: 'Please wait before resending',
  verificationSuccess: 'Email verified successfully!',
  registrationComplete: 'Registration completed successfully',
  sessionExpired: 'Session expired. Please sign up again.',
  emailNotFound: 'Email not found. Please sign up again.',

  forgotLoading: 'Sending reset link...',
  forgotEmailRequired: 'Enter your email on the login form, then click Forgot password.',
  forgotSuccessTitle: 'Check your email',
  forgotSuccessMessage:
    'Password reset link has been sent to your registered email address. Please check your inbox and follow the instructions to reset your password.',
  backToLogin: 'Back to login',

  resetTitle: 'Reset password',
  resetDescription: 'Enter a new password for your account.',
  newPassword: 'New Password',
  confirmPassword: 'Confirm Password',
  resetButton: 'Update password',
  resetUpdating: 'Updating password...',
  resetSuccess: 'Password updated successfully.',
  resetWelcomeBack: 'Welcome back!',
  resetInvalidTitle: 'Reset link unavailable',
  resetInvalidDefault: 'This reset link is invalid.',
}

export const LANDING_CONTENT = {
  badge: 'Restaurant Management Platform',
  heroTitle: 'Manage Your Restaurant',
  heroHighlight: 'Digitally',
  heroDescription:
    'Foodify helps you run smarter operations with QR-based ordering, real-time menu management, order tracking, and sales analytics — all in one modern dashboard.',
  ctaLogin: 'Login',
  ctaSignup: 'Sign Up',
  featuresTitle: 'Everything you need to grow',
  featuresDescription:
    'From front-of-house to back-office, Foodify streamlines how you serve customers and understand your business.',
  ctaSectionTitle: 'Ready to digitize your restaurant?',
  ctaSectionDescription:
    'Join Foodify today and start managing orders, menus, and analytics in minutes.',
  ctaGetStarted: 'Get Started Free',
  ctaLoginDashboard: 'Login to Dashboard',
  features: [
    {
      title: 'QR-Based Ordering',
      description: 'Let guests scan table QR codes and place orders instantly from their phones.',
    },
    {
      title: 'Menu Management',
      description: 'Add, edit, and organize menu items with categories and availability controls.',
    },
    {
      title: 'Order Tracking',
      description: 'Monitor live orders, update statuses, and keep your kitchen in sync.',
    },
    {
      title: 'Sales Analytics',
      description: 'Track daily, weekly, and monthly performance with actionable insights.',
    },
  ],
}

export const DASHBOARD_CONTENT = {
  title: 'Dashboard',
  description: 'Overview of your restaurant performance',
  today: 'Today',
  yesterday: 'Yesterday',
  last7Days: 'Last 7 Days',
  last30Days: 'Last 30 Days',
  customDate: 'Custom',
  todayOrders: "Today's Orders",
  todayRevenue: "Today's Revenue",
  pendingOrders: 'Pending Orders',
  completedOrders: 'Completed Orders',
  cancelledOrders: 'Cancelled Orders',
  activeTables: 'Active Tables',
  dailySales: 'Daily Sales',
  totalOrders: 'Total Orders',
  totalRevenue: 'Total Revenue',
  avgOrderValue: 'Average Order Value',
  peakTime: 'Peak Ordering Time',
  salesOverview: 'Sales Overview',
  orderStatus: 'Order Status',
  recentOrders: 'Recent Orders',
  viewOrder: 'View',
  logoutSuccess: 'Logged out successfully.',
}

export const TIMESLOTS_CONTENT = {
  title: 'Time Slot Management',
  description: 'Configure daily ordering windows for your restaurant',
  add: 'Add Time Slot',
  edit: 'Edit Time Slot',
  slotName: 'Slot Name',
  slotNamePlaceholder: 'e.g. Breakfast, Lunch, Dinner',
  fromTime: 'From Time',
  toTime: 'To Time',
  status: 'Status',
  createdDate: 'Created Date',
  actions: 'Actions',
  active: 'Active',
  inactive: 'Inactive',
  enabled: 'Active',
  disabled: 'Inactive',
  enable: 'Enable',
  disable: 'Disable',
  all: 'All',
  filterActive: 'Active only',
  filterInactive: 'Inactive only',
  searchPlaceholder: 'Search by slot name...',
  clearFilters: 'Clear filters',
  save: 'Save Time Slot',
  saving: 'Saving...',
  created: 'Time slot created successfully',
  updated: 'Time slot updated successfully',
  deleted: 'Time slot deleted successfully',
  statusToggled: 'Time slot status updated',
  deleteTitle: 'Delete time slot?',
  deleteDescription: 'This action cannot be undone. Customers will no longer see this ordering window.',
  deleteConfirm: 'Delete',
  deleting: 'Deleting...',
  emptyTitle: 'No time slots yet',
  emptyDescription: 'Create time slots so customers can order during Breakfast, Lunch, Dinner, and more.',
  emptyCta: 'Create Your First Time Slot',
  noResultsTitle: 'No matching time slots',
  noResultsDescription: 'Try adjusting your search or filters.',
  validation: {
    slotNameRequired: 'Slot name is required',
    fromTimeRequired: 'From time is required',
    toTimeRequired: 'To time is required',
    invalidRange: 'From time must be earlier than to time',
    equalTimes: 'From and to time cannot be the same',
  },
  pagination: {
    showing: 'Showing',
    of: 'of',
    records: 'records',
    rowsPerPage: 'Rows per page',
    page: 'Page',
  },
}

export const ORDERS_CONTENT = {
  title: 'Orders',
  description: 'Track and manage customer orders',
  searchPlaceholder: 'Search by order ID or table...',
  allStatuses: 'All statuses',
  statusUpdated: 'Order status updated',
}

export const QR_CONTENT = {
  title: 'QR Codes',
  description: 'Create, print, and manage table QR codes',
  tableNumber: 'Table number',
  tableName: 'Table name',
  generate: 'Create table',
  generated: 'Table & QR created',
  regenerated: 'QR code regenerated',
  removed: 'Table removed',
  bulkTitle: 'Bulk create',
  bulkCreate: 'Create all tables',
  bulkPreview: 'Preview',
  bulkConfirm: 'Confirm & create',
  bulkSuccess: 'Tables created successfully',
  downloadZip: 'Download all (ZIP)',
  downloadPdf: 'Download all (PDF)',
  printAll: 'Print all',
  totalTables: 'Total tables',
  activeTables: 'Active',
  disabledTables: 'Disabled',
  totalQr: 'QR codes',
  quickCreate: 'Quick create',
  searchPlaceholder: 'Search by name or number...',
  filterAll: 'All',
  filterActive: 'Active',
  filterDisabled: 'Disabled',
  sortLatest: 'Latest',
  sortOldest: 'Oldest',
  sortNumber: 'Table number',
  selected: 'selected',
  downloadSelected: 'Print selected',
  disableSelected: 'Disable selected',
  deleteSelected: 'Delete selected',
  selectAll: 'Select all',
  clearSelection: 'Clear',
  view: 'View',
  download: 'Download',
  print: 'Print',
  regenerate: 'Regenerate',
  disable: 'Disable',
  enable: 'Enable',
  delete: 'Delete',
  prefix: 'Prefix',
  startNumber: 'Start number',
  count: 'Number of tables',
}

export const PROFILE_CONTENT = {
  title: 'Profile',
  description: 'Manage your restaurant account, branding, and security',
  save: 'Save changes',
  saving: 'Saving...',
  saved: 'Profile updated',
  restaurantInfo: 'Restaurant information',
  branding: 'Branding',
  passwordSecurity: 'Password & security',
  logoUpload: 'Restaurant logo',
  logoHint: 'JPG, PNG or WEBP · Max 5 MB',
  removeLogo: 'Remove logo',
  changePassword: 'Change password',
  forgotPassword: 'Forgot password?',
  currentPassword: 'Current password',
  newPassword: 'New password',
  confirmPassword: 'Confirm password',
  updatePassword: 'Update password',
  passwordChanged: 'Password changed successfully',
}

export const SETTINGS_CONTENT = {
  title: 'Settings',
  description: 'Account and security preferences',
  changePassword: 'Change Password',
  updatePassword: 'Update Password',
  updating: 'Updating...',
  passwordChanged: 'Password changed',
}

export const NOT_FOUND_CONTENT = {
  title: 'Page not found',
  description: 'The page you are looking for does not exist or has been moved.',
}

export const ERROR_BOUNDARY_CONTENT = {
  title: 'Something went wrong',
  description: 'An unexpected error occurred. Please refresh the page or try again later.',
}

export const ROUTE_LOADING_CONTENT = {
  label: 'Loading page',
  message: 'Loading...',
}
