export const CUSTOMER_CONTENT = {
  tabMenu: 'Menu',
  tabOrders: 'Orders',
  tabAbout: 'About',
  aboutDescription: 'About us',
  aboutPhone: 'Contact',
  aboutEmail: 'Email',
  aboutLocation: 'Location',
  aboutHours: 'Business hours',
  callRestaurant: 'Call restaurant',
  gstLabel: 'GST',
  fssaiLabel: 'FSSAI',
  orderingFrom: 'Ordering from',
  table: 'Table',
  add: 'ADD',
  viewCart: 'View Cart',
  itemsAdded: 'items',
  cart: 'Your Cart',
  emptyCart: 'Your cart is empty',
  browseMenu: 'Browse Menu',
  continueShopping: 'Continue Shopping',
  browseMore: 'Browse More Items',
  applyCoupon: 'Apply',
  couponPlaceholder: 'Enter coupon code',
  subtotal: 'Subtotal',
  discount: 'Discount',
  taxes: 'GST',
  grandTotal: 'To Pay',
  paymentMethod: 'Payment Method',
  payLater: 'Pay After Food Delivery',
  payLaterDesc: 'Pay when your order is served at the table',
  onlinePayment: 'Online Payment',
  comingSoon: 'Coming Soon',
  placeOrder: 'Place Order',
  proceedCheckout: 'Proceed to Checkout',
  placingOrder: 'Placing order...',
  orderSuccess: 'Order placed successfully',
  orderNumber: 'Order Number',
  orderTotal: 'Total',
  orderTime: 'Order Time',
  trackOrder: 'Track Order',
  refreshStatus: 'Refresh Status',
  gstIncluded: 'GST',
  yourActiveOrder: 'Your Active Order',
  orderHistory: 'Recent Orders',
  noActiveOrders: 'No active orders',
  statusLabel: 'Status',
  activeOrder: 'Active order',
  viewDetails: 'View details',
  cancelOrder: 'Cancel Order',
  cancelling: 'Cancelling...',
  cancelConfirm: 'Are you sure you want to cancel this order?',
  cancelSuccess: 'Your order has been cancelled.',
  sessionExpired: 'Session expired. Please scan the QR code again.',
}

export const CUSTOMER_STATUS = {
  placed: 'Placed',
  confirmed: 'Confirmed',
  preparing: 'Preparing',
  ready: 'Ready',
  served: 'Served',
  completed: 'Completed',
  cancelled: 'Cancelled',
}
