export const MENU_CONTENT = {
  title: 'Menu Management',
  description: 'Manage time-slot and all-day foods for your restaurant',
  addFood: 'Add Food',
  editFood: 'Edit Food',
  foodName: 'Food Name',
  foodNamePlaceholder: 'e.g. Idly, Meals, Water Bottle',
  price: 'Price',
  pricePlaceholder: '0.00',
  gstPercentage: 'GST %',
  gstHint: 'GST is calculated on the server when customers place orders',
  description: 'Description',
  descriptionPlaceholder: 'Optional description for customers',
  foodType: 'Food Type',
  allDay: 'Available All Day',
  timeSlotBased: 'Time Slot Based',
  timeSlot: 'Time Slot',
  selectTimeSlot: 'Select a time slot',
  noTimeSlots: 'Create active time slots first to assign slot-based foods.',
  status: 'Status',
  active: 'Active',
  inactive: 'Inactive',
  actions: 'Actions',
  typeAllDay: 'Available All Day',
  typeTimeSlot: 'Time Slot Based',
  save: 'Save Food',
  saving: 'Saving...',
  created: 'Food added successfully',
  updated: 'Food updated successfully',
  deleted: 'Food deleted successfully',
  statusToggled: 'Food status updated',
  saveFailed: 'Failed to save food',
  deleteTitle: 'Delete this food item?',
  deleteDescription: 'This will permanently remove the item from your menu.',
  deleteConfirm: 'Delete',
  deleting: 'Deleting...',
  searchPlaceholder: 'Search by food name...',
  filterAll: 'All',
  filterActive: 'Active',
  filterInactive: 'Inactive',
  filterTimeSlot: 'Time Slot Foods',
  filterAllDay: 'All-Day Foods',
  clearFilters: 'Clear filters',
  sortLatest: 'Latest First',
  sortOldest: 'Oldest First',
  sortPriceLow: 'Price: Low to High',
  sortPriceHigh: 'Price: High to Low',
  sortName: 'Name A-Z',
  emptyTitle: 'Your menu is empty',
  emptyDescription: 'Add breakfast specials, lunch meals, or all-day drinks to start taking orders.',
  emptyCta: 'Add Your First Food',
  noResultsTitle: 'No foods match your filters',
  noResultsDescription: 'Try a different search or reset your filters.',
  stats: {
    total: 'Total Foods',
    active: 'Active Foods',
    inactive: 'Inactive Foods',
    timeSlot: 'Time Slot Foods',
    allDay: 'All-Day Foods',
  },
  pagination: {
    showing: 'Showing',
    of: 'of',
    records: 'foods',
    rowsPerPage: 'Rows per page',
    page: 'Page',
  },
  validation: {
    nameRequired: 'Food name is required',
    priceRequired: 'Price is required',
    priceInvalid: 'Price must be greater than 0',
    timeSlotRequired: 'Please select a time slot',
    gstRequired: 'Select a valid GST rate',
  },
}

export const GST_OPTIONS = [0, 5, 12, 18, 28]
